// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: currency.sql

package db

import (
	"context"
)

const addCurrency = `-- name: AddCurrency :one
INSERT INTO currency ("desc") VALUES (
  $1
) RETURNING "desc"
`

func (q *Queries) AddCurrency(ctx context.Context, desc string) (string, error) {
	row := q.db.QueryRowContext(ctx, addCurrency, desc)
	err := row.Scan(&desc)
	return desc, err
}
